# Generated by Django 4.2.6 on 2024-10-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, choices=[('living_room_furniture', 'Living Room Furniture'), ('bedroom_furniture', 'Bedroom Furniture'), ('kitchen_furniture', 'Kitchen Furniture'), ('dining_room_furniture', 'Dining Room Furniture'), ('outdoor_furniture', 'Outdoor Furniture'), ('office_furniture', 'Office Furniture'), ('bathroom_furniture', 'Bathroom Furniture'), ('kids_furniture', 'Kids Furniture'), ('entryway_furniture', 'Entryway Furniture')], max_length=60, null=True),
        ),
    ]
